---
- name: installed selinux modules
  dnf:
    name: "{{ items }}"
    state: present
  with_items:
    - libselinux-python3
    - libsemanage-python3

- name: disabled selinux
  selinux:
    state: disabled
