---
- name: installed docker for rhel family task yaml
  include: disable_selinux.yml
  when: ansible_os_family == "RedHat"

- name: reboot to disable SELinux
  reboot:
  when: ansible_os_family == "RedHat"
