---
- name: apt updated
  apt:
    update_cache: yes

- name: pre installed software
  apt:
    name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present
