---
- name: installed docker for debian family task yaml
  include: debian.yml
  when: ansible_os_family == "Debian"

- name: installed docker for rhel family task yaml
  include: rhel.yml
#  when: ansible_os_family == "RedHat"

- name: setted up 
  include: setting_up.yml
