---
- name: installed docker repo
  get_url:
    url: 'https://download.docker.com/linux/centos/docker-ce.repo'
    dest: /etc/yum.repos.d/

- name: installed docker packages
  dnf:
    name:
      - "docker-ce-{{ docker-ce_ver }}"
      - "docker-ce-cli-{{ docker-ce_ver }}"
      - "containerd.io-{{ containerd-io_ver }}"
      - "docker-compose-plugin-{{ docker-compose_ver }}"
    state: present
  notify:
    - created docker group
    - added "{{ docker_user }}" to docker group
    - pushed ssh pub key for "{{ docker_user }}"
    - started docker
