---
- name: installed docker repo
  dnf:
    name: https://download.docker.com/linux/rhel/docker-ce.repo

- name: installed docker packages
  dnf:
    name: "{{ items }}"
    state: present
  with_items:
    - "docker-ce-{{ docker_ce_ver }}"
    - "docker-ce-cli-{{ docker_ce_ver }}"
    - "containerd.io-{{ containerd_io_ver }}"
    - "docker-compose-plugin-{{ docker_compose_ver }}"
  notify:
    - created docker group
    - added "{{ docker_user }}" to docker group
    - pushed ssh pub key for "{{ docker_user }}"
    - started docker
