---
- name: installed docker repo
  get_url:
    url: 'https://download.docker.com/linux/centos/docker-ce.repo'
    dest: /etc/yum.repos.d/

- name: installed docker packages
  dnf:
    name:
      - "docker-ce-{{ docker_ce_ver }}"
      - "docker-ce-cli-{{ docker_ce_ver }}"
      - "containerd.io-{{ containerd_io_ver }}"
      - "docker-compose-plugin-{{ docker_compose_ver }}"
    state: present
