---
- name: created docker group
  group:
    name: docker
    state: present

- name: added "{{ docker_user }}" to docker group
  user:
    name: "{{ docker_user }}"
    group: docker
    append: yes

- name: mkdir .ssh dir
  file:
    path: "/home/{{ docker_user }}/.ssh"
    owner: "{{ docker_user }}"
    group: docker
    mode: 0700
    state: directory

- name: pushed ssh pub key for "{{ docker_user }}"
  template:
    src: docker_id_rsa.pub.j2
    dest: "/home/{{ docker_user }}/.ssh/authorized_keys"
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    mode: 0400

- name: started docker
  systemd:
    name: docker
    state: started
    enabled: yes
